from enum import Enum, unique

@unique
class ErrorHandler(Enum):
    ERROR_KEY_LENGTH = "INCORRECT KEY LENGTH"
    ERROR_FEISTEL_MESSAGE_LENGTH = "ERROR OCCURRED DURING ENCRYPTION"
    ERROR_CONVERTING_TO_STRING = "ERROR WHILE CONVERTING INTEGER TO NUMERAL STRING"
    ERROR_EMPTY_MESSAGE = "MESSAGE LENGTH CANNOT BE 0"
    ERROR_INVALID_PAD = "MESSAGE WAS NOT CORRECTLY PADDED"

    def __str__(self):
        return self.value

